### ISSUE TITLE
YAML editor not showing up when using Safari

### ISSUE THREAD

**Issue by joerikosters** [Sian-Lee-SA/Home-Assistant-Switch-Manager#126]
After a long-long search why I couldn't find the YAML editor when pressing "edit in YAML" or "variables" I figured out don't get the yaml input field at all when using Safari...

After a few hours of thinking I am just not looking in the right place I tried it in chrome and the field showed up...

<img width="2198" alt="Screenshot 2023-05-13 at 21 54 43" src="https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/87047885/93a47a4f-91a1-4107-9a89-5b2c72fdc207">
<img width="2198" alt="Screenshot 2023-05-13 at 21 55 27" src="https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/87047885/cc1c728c-7be4-408f-8727-539afc5bf4fd">

**Comment by joerikosters** [comment]
I DO get the YAML editor in all other (normal) automations while using HA in Safari

**Comment by Sian-Lee-SA** [comment]
Could you post the console logs for Safari as I don't have access to that browser to debug

**Comment by joerikosters** [comment]
If you click the yaml editor, or variables you get this:
<img width="2560" alt="Screenshot 2023-05-15 at 02 49 05" src="https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/87047885/a0945440-ad5f-44f8-ae30-1557662bb669">

**Comment by Sian-Lee-SA** [comment]
So I did some digging around but can't find anything from my code that stands out to be causing this. As the stacktrace delves into the derived Home Assistant frontend code it becomes more complicated to scope on. Unless someone with experience with Web dev and has Safari to debug then there's not much that can be done atm (from my end) otherwise it would be like trying to hit a target blindfolded.

I may install a Hackintosh on a VM sometime in the near future then be able to tackle this but until then I can be of much help.

**Comment by mundschenk-at** [comment]
@Sian-Lee-SA I have previously seen the same issue in some other integration/add-on, unfortunately I can't remember which. Are there any JS dependencies you could have to update?
