### ISSUE TITLE
Actions show as 'Unknown' in the visual editor in 2024.8

### ISSUE THREAD

**Issue by genehand** [Sian-Lee-SA/Home-Assistant-Switch-Manager#244]
There's a cosmetic issue after the renaming of "services" to "actions" in 2024.8.  Everything seems to be working correctly, but actions aren't recognized:

<img width="519" alt="Screenshot 2024-08-12 at 5 13 22 PM" src="https://github.com/user-attachments/assets/cd6dd163-5878-4830-9e21-a80ad710d7f2">

**Comment by Sian-Lee-SA** [comment]
As the UI is compiled with an earlier version of the frontend, it's best to stick with the service naming instead. I will make note of this in the readme. The UI hasn't been recompiled with the latest frontend version of HA because it involves serious restructures and tracing which I don't have the time for and not a quick job.

**Comment by hesspoint** [comment]
Unfortunately it does not work. When I change "action" to "service" in the config of my rempote and save it and open it again it is again changed to action. I think I read that HA automatically changes automations from service to action once they are edited and saved. I guess that is the issue here too. Any ideas how to solve this?

**Comment by Sian-Lee-SA** [comment]
It was my understanding from the blog update post that service name was still being respected. Unfortunately it seems based on your experience that they're trying to push the new action naming scheme discreetly through backend processing. I'm still running an older version of HA so won't be able to investigate until I decide to update. Personally, I hate updating more and more when new releases come out and I'm just getting tired of having to fix everything (not just my code but every other integration added too) and dealing with their constant changes.

**Comment by Hypfer** [comment]
@Sian-Lee-SA Would it maybe be a better approach to not bundle the HA frontend components at compile time but instead just reference those that are part of the frontend of the HA install?
Genuine question. I'm unsure what the better approach is there.

One downside of that approach is that you will have to trick the lazy loading feature of the frontend so that the UI elements you're referencing are actually available. That can be done like this:
https://github.com/thomasloven/hass-browser_mod/blob/de87d5b4f57e2f0d02ad2868e5532ddcac296359/js/helpers.ts#L106-L122

I've been using that approach for https://github.com/Hypfer/hass-scene_presets which was greatly inspired by your work here so thank you for that! Switch Manager is great and continues to provide a lot of value to me :)

**Comment by Sian-Lee-SA** [comment]
You are correct and I used that approach very early on but for the life of me I can't remember why I had to compile it myself, I think it was due to some confictions or something... I think before I try building again, I will try using it directly from HA internal but it will probably end up reminding me why compiling from their source code was the right approach.
