### ISSUE TITLE
Support for double press and hold on Lutron Caseta remotes?

### ISSUE THREAD

**Issue by darrendavid** [Sian-Lee-SA/Home-Assistant-Switch-Manager#261]
Is there support for double press and/or hold on Lutron Caseta remotes, or just press events?

**Comment by Sian-Lee-SA** [comment]
You'll have to check with your device and the service your using, Switch Manager doesn't implement devices from their native capabilities, it literally just binds them and acts as a middle man. If your device is supported but the current blueprint hasn't implemented those functions, then you can update that blueprint easily. Otherwise you can get creative and implement it through your sequence and actions...
