### ISSUE TITLE
"Copy From" missing select

### ISSUE THREAD

**Issue by iceboundflame** [Sian-Lee-SA/Home-Assistant-Switch-Manager#262]
After updating to v2.0.0, the "Copy From" menu doesn't show a dropdown to select source.

<img width="825" alt="Screenshot 2024-09-23 at 17 11 36" src="https://github.com/user-attachments/assets/a0f674ea-3270-4924-80f3-bb6f425971a7">

**Comment by Sian-Lee-SA** [comment]
currently fixed and will be in next release

**Comment by cameronkelley** [comment]
@Sian-Lee-SA - I see it's supposed to be fixed in dc3b643855ebd1adf6d5f3fe861a5b63d146deea. Would it be possible to release the current changes as a pre-release so it's more "opt-in" to get this fix until you release the next version? I'm slowly installing a lot of new switches and the copy feature would really help.
