### ISSUE TITLE
Idea: Show configured buttons

### ISSUE THREAD

**Issue by noxhirsch** [Sian-Lee-SA/Home-Assistant-Switch-Manager#28]
Another idea came to my mind: Show which buttons are configured. 
Icons (`mdi:gesture-tap` `mdi:gesture-double-tap` `mdi:gesture-tap-hold`) on the buttons show, which type of tap-action is configured. The icons would need to be very small since buttons can be very small and need to have an outline or background to be visible on dark and light switch pictures.

![image](https://user-images.githubusercontent.com/30938717/209563565-39b60373-f026-4158-ba16-c39ac713c257.png)

By the way: It's your project and your time - so it's all good if you don't like my ideas or don't care about them and close these issues without commenting on them!

**Comment by Sian-Lee-SA** [comment]
Not sure if you've noticed but I did implement something to visualise that a button had been configured because I wanted this for myself. It's very subtle because I didn't want it to again "be in your face" but non configure buttons have a greyish background where as configured buttons will be transparent... within that I added a number of sequences next to the actions so you can see which actions are set when a button is selected

**Comment by Sian-Lee-SA** [comment]
Buttons also come in all shapes and sizes aswell with blueprints as there are circle shapes aswell as path shapes so knowing where a button is located and if it has enough room to fit icons within is very problematic

**Comment by Sian-Lee-SA** [comment]
There are also devices that have 5 or so taps or presses then there are hold and hold (release) actions also so it could start to look really cluttered

**Comment by noxhirsch** [comment]
Now that you mention it, I see it that non-configured buttons are grayed out. However, my goal is not to see if buttons are not yet configured, but rather if there are slots free that I can assign a function to.
If there are sometimes 5 different taps, icons are rather not so good, I agree with you. What would you think alternatively of a display in numbers like "configured/available"? For example 0/2 or 3/5 - this could be very small and maybe even have reduced opacity. This should even fit very small buttons.
![image](https://user-images.githubusercontent.com/30938717/209567651-4d3ed1ea-47e0-44d6-b319-5ee6ff9436a2.png)

**Comment by Sian-Lee-SA** [comment]
Again though, Because svg and the circle and path elements can be really hard to map extra elements to, this is can become a job and a half. The other thing is, generally with many switches like the philips hue etc. You want those switches to be handled by the bridge and not switch manager, same goes for bindings in Zigbee2MQTT and even ZWave where it's better to bind buttons to lights etc straight from their eco system, so the idea of having empty buttons and actions should be common and adding empty visualisations of what actions arent set is redundant for those switches. While I get where you're coming from and I agree that in a way it would be good on certain occassions to reflect what button is set and what isn't I think how it is atm is informative enough (being greyed out and selecting a non greyed out button then seeing the number of sequences next to an action) is viable. Normally  people will set their switches initially and know step by step in how they want their buttons mapped. On rare occassions I can assume this would be reconfigured but generally users have an idea on what button and action they're initially going to map without needing to know how many actions are set on a button.
