### ISSUE TITLE
[Feature Request] Set LED on switch

### ISSUE THREAD

**Issue by fbjerggaard** [Sian-Lee-SA/Home-Assistant-Switch-Manager#296]
I have some switches that has LED's on them - some have 1 RGB LED for each button and some have just 1 LED for the entire switch.

It would be really awesome if this integration could also be used to set the state of the LED's along with pressing the buttons

**Comment by Sian-Lee-SA** [comment]
Switch MJanager is a **not** a state machine and holds no states. Home Assistant already has this capability and due to the dynamic nature of a led representation/reflection on a state and how and/or why then it is better handled by home assistant instead of recreating the wheel. Things like a boolean helper targetting the MQTT topic or restful (depending on the service) would be my goto.
