### ISSUE TITLE
Proposal: Agree on naming of actions in blueprints

### ISSUE THREAD

**Issue by cdjm** [Sian-Lee-SA/Home-Assistant-Switch-Manager#30]
Maybe it is a good idea to agree on the naming of actions:

Some blueprints use tap, double tap and hold.
Some use press, long press, long press (released).

This should be harmonized for all blueprints sooner or later.

I feel this component has a potential to join the HA core so there should be no blocking points for adding translation later on.
Or is it too early to think about such things?

**Comment by Sian-Lee-SA** [comment]
I agree but not every switch is the same. For example a mechanical switch is a push or press where as a touch device like my Quadmote is a tap/touch action. While tap doesn't make sense for mechanical devices I can assume press would probably be the goto as this can reflect both mechanical and touch devices. 

But having said that, it's just a descriptive term and not referenced in code in anyway so it's really a matter of how the blueprint designer wishes to present their naming for actions (this is also normally reflected how the event or mqtt describes the action). I also don't like being a regulated nuesance either where this has to be like this and that has to be like that because it can be really off putting for contributers as I personally get annoyed when I have to go back and change things over and over again to conform with other regulated repo's that I do PR's for.

As of now I'll just leave it up to the contributors in how they want to name it just to not be so regulated and more inviting but I will mention logical changes in PR's where it would avoid future conflicts if there was to be a logical change (for example your PR for the hue dimmer as swapping the buttons later on would cause wrong actions on their already set buttons).

Down the track this might change and be more conforming but if and when that does happen it's just a matter of changing each blueprint's action name which wouldn't take long anyway.

**Comment by Sian-Lee-SA** [comment]
Naming convention has been added to README and blueprints has been updated to reflect these
